//
//  WeatherAPI.swift
//  Traviler
//
//  Created by Mohammed Iskandar on 27/12/2020.
//

import Foundation
import CoreLocation

/**
 Router protocol for Weather API,
 This Router is mainly used to get data from `https://api.weatherapi.com`.
 
 API Key: The authenticaiton token thet've been generated by Weather API to allow communication between client (Taviler Application) and server (Weather API). This key generated from a free account, so their will be some limitation in data that'll be provided by API provider.
 
 Endpoints:
    * Each endpoint is written as : `case [HTTP METHOD][METHOD NAME]`, but in `camleCase`. (see `case getCurrentWeather`)
        - `[HTTP METHOD]` can be on of the http available methods (GET, POST, PUT, DELETE.. etc).
        - `[METHOD NAME]` is the method name as described by API provider.
        - After each endpoint decleration, the remote URL for the API docs of that is endpoint is provided. (see `case getCurrentWeather`)
 */
enum WeatherRouter: Router {
    
    private static var apiKey: String = "334ab64bc83c4de4ae5143456202712"
    static var baseURL: URL? = URL(string: "https://api.weatherapi.com/v1")
    
    case getCurrentWeather(at: CLLocationCoordinate2D)
    case getForecast(days: Int, at: CLLocationCoordinate2D)
    
    var method: HTTPMethod {
        return .get
    }
    
    var path: String {
        switch self {
        case .getCurrentWeather:
            return "/current.json"
            
        case .getForecast:
            return "/forecast.json"
            
        }
    }
    
    var parameters: Parameters? {
        switch self {
        case .getCurrentWeather(at: let coordinate):
            var parameters: Parameters = [:]
            
            parameters.value("\(coordinate.latitude),\(coordinate.longitude)", forKey: "q")
            
            return parameters
            
        case .getForecast(days: let days, at: let coordinate):
            var parameters: Parameters = [:]
            
            parameters.value(days, forKey: "days")
            parameters.value("\(coordinate.latitude),\(coordinate.longitude)", forKey: "q")
            
            return parameters
        }
    }
    
    var accessType: AccessType? {
        return .publicRoute
    }
    
    func asURLRequest() throws -> URLRequest {
        var urlRequest = URLRequest(url: WeatherRouter.baseURL!.appendingPathComponent(path))
        
        urlRequest.httpMethod = method.rawValue
        
        urlRequest.addValue(ContentType.json.rawValue, forHTTPHeaderField: HTTPHeaderField.acceptType.rawValue)
        urlRequest.addValue(ContentType.json.rawValue, forHTTPHeaderField: HTTPHeaderField.contentType.rawValue)
        
        do {
            if method == .get {
                urlRequest.queryItems = parameters!.toURLQueryItems()
            } else {
                urlRequest.httpBody = try JSONSerialization.data(withJSONObject: parameters!, options: [])
            }
        } catch {
            throw ParametersError.encodingError
        }
        
        urlRequest.queryItems?.append(URLQueryItem(name: "key", value: WeatherRouter.apiKey))
        
        return urlRequest;
    }
}
